---
title: "Estimation Results of Bayesian hierarchical NHPP"
author: "Miao Cai <miao.cai@slu.edu>"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2: 
    number_sections: true
    toc: yes
header-includes:
  - \usepackage{soul}
  - \usepackage{float}
#  - \usepackage[table]{xcolor}
  - \usepackage{setspace}\linespread{1.2}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.height = 4, fig.pos = "H")
```

\clearpage

```{r}
pacman::p_load(data.table, dplyr, ggplot2, purrr)

read_all <- function(file_path = "fit/hierarchical_NHPP20190713/"){
  est_df = file_path %>% 
    list.files() %>% 
    map_dfr(function(file_name){
      fread(paste0(file_path, file_name)) %>% 
        mutate(id = gsub(".csv", "", file_name)) %>% 
        mutate(id = gsub("_.*", "", id)) %>% 
        mutate(id = gsub("sim", "", id)) %>% 
        mutate(id = as.integer(id))
    }) %>% 
    group_by(term, id) %>% 
    summarise(est_mean = mean(estimate),
              est_sd = sd(estimate)) %>% 
    arrange(term, id)

  return(est_df)
}

plot_est = function(data, var = "beta", hline_var = 1.5){
  p = data %>% 
    filter(term == var) %>% 
    ggplot(aes(id, est_mean)) + 
    geom_point() + 
    geom_line(linetype = "dashed", color = "red")+
    geom_errorbar(aes(ymax = est_mean + 1.96*est_sd,
                      ymin = est_mean - 1.96*est_sd), 
                  width = 1)+
    geom_segment(aes(x = 10, xend = 100, 
                     y = hline_var, yend = hline_var), 
                 color = "green")+
    scale_x_continuous(breaks = c(0, 10, 25, 50, 75, 100),
                       labels = c("0", "10", "25", "50", "75", "100")) +
    labs(x = "The number of drivers (random effects)",
         y = var) +
    theme_bw()
  return(p)
}
```


100 simulation on 2019-07-14
============================

```{r}
est_df1 = read_all("fit/hierarchical_NHPP20190714/")
```

## beta

```{r}
plot_est(est_df1, "beta", 1.5)
```


## mu0

```{r}
plot_est(est_df1, "mu0_true", 0.2)
```


## sigma0

```{r}
plot_est(est_df1, "sigma0", 0.5)
```


## Fixed parameters

```{r}
r1 = plot_est(est_df1, "R1_K[1]", 1)
r2 = plot_est(est_df1, "R1_K[2]", 0.3)
r3 = plot_est(est_df1, "R1_K[3]", 0.2)
```

```{r fig.height=10, fig.width=8}
gridExtra::grid.arrange(r1, r2, r3)
```

3000 simulations
================

```{r}
est_df2 = read_all("fit/hierarchical_NHPP20190715/")
```
## beta

```{r}
plot_est(est_df2, "beta", 1.5)
```

## mu0

```{r}
plot_est(est_df2, "mu0_true", 0.2)
```

## Sigma0

```{r}
plot_est(est_df2, "sigma0", 0.5)
```

## Fixed-effect parameters

```{r}
r1 = plot_est(est_df2, "R1_K[1]", 1)
r2 = plot_est(est_df2, "R1_K[2]", 0.3)
r3 = plot_est(est_df2, "R1_K[3]", 0.2)
```

```{r fig.height=10, fig.width=8}
gridExtra::grid.arrange(r1, r2, r3)
```
