---
title: "Conquer zero-event issue in hierarchical NHPP"
author: "Miao Cai <miao.cai@slu.edu>"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2: 
    number_sections: true
    toc: true
header-includes:
  - \usepackage{soul}
  - \usepackage{float}
#  - \usepackage[table]{xcolor}
  - \usepackage{setspace}\linespread{1.4}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r eval = FALSE}
pacman::p_load(rstan, tidyverse, data.table)
source("functions/NHPP_functions.R")
# source to import sim_hier_nhpp() and plot_est()
```

```{r test, eval = FALSE}
# sampling from Stan
df = sim_hier_nhpp(D = 10, beta = 1.5)
f = stan("stan/nhppnoevent_lp.stan",
         chains = 1, iter = 1000, data = df$hier_dat)
f = broom::tidy(f)

f1 = stan("stan/nhppnoevent_lp.stan",
         chains = 1, iter = 1000, data = df$hier_dat)
f1 = broom::tidy(f1)

df$true_params$mu0
df$true_params$sigma0
df$true_params$r1_rk
# check estimation results
# f
# df$true_params
```

```{r simulation, eval=FALSE}
set.seed(123)
sim10 = list()
for (i in 1:500) {
  print(paste0("D = 10: ", i, " (out of 500)"))
  z = sim_hier_nhpp(D = 10)
  tryCatch({fit0 = stan("stan/nhppnoevent_lp.stan",
                        chains = 1, iter = 1000, 
                        data = z$hier_dat, seed = 123
  )}, error=function(e){})
  
  sim10[[i]] = pull_use("mu0_true|sigma0|beta|R1_K", fit0)
}
data.table::fwrite(data.table::rbindlist(sim10), 
                   "fit/Conquer_no_events_20190715/sim10.csv")


sim25 = list()
for (i in 1:500) {
  print(paste0("D = 25: ", i, " (out of 500)"))
  z = sim_hier_nhpp(D = 25)
  tryCatch({fit0 = stan("stan/nhppnoevent_lp.stan",
                        chains = 1, iter = 1000, 
                        data = z$hier_dat, seed = 123
  )}, error=function(e){})
  
  sim25[[i]] = pull_use("mu0_true|sigma0|beta|R1_K", fit0)
}
data.table::fwrite(data.table::rbindlist(sim25), 
                   "fit/Conquer_no_events_20190715/sim25.csv")

sim50 = list()
for (i in 1:500) {
  print(paste0("D = 50: ", i, " (out of 500)"))
  z = sim_hier_nhpp(D = 50)
  tryCatch({fit0 = stan("stan/nhppnoevent_lp.stan",
                        chains = 1, iter = 1000, 
                        data = z$hier_dat, seed = 123
  )}, error=function(e){})
  
  sim50[[i]] = pull_use("mu0_true|sigma0|beta|R1_K", fit0)
}
data.table::fwrite(data.table::rbindlist(sim50), 
                   "fit/Conquer_no_events_20190715/sim50.csv")


sim75 = list()
for (i in 1:500) {
  print(paste0("D = 75: ", i, " (out of 500)"))
  z = sim_hier_nhpp(D = 75)
  tryCatch({fit0 = stan("stan/nhppnoevent_lp.stan",
                        chains = 1, iter = 1000, 
                        data = z$hier_dat, seed = 123
  )}, error=function(e){})
  
  sim75[[i]] = pull_use("mu0_true|sigma0|beta|R1_K", fit0)
}
data.table::fwrite(data.table::rbindlist(sim75), 
                   "fit/Conquer_no_events_20190715/sim75.csv")


sim100 = list()
for (i in 1:500) {
  print(paste0("D = 100: ", i, " (out of 2000)"))
  z = sim_hier_nhpp(D = 100)
  tryCatch({fit0 = stan("stan/nhppnoevent_lp.stan",
                        chains = 1, iter = 1000, 
                        data = z$hier_dat, seed = 123
  )}, error=function(e){})
  
  sim100[[i]] = pull_use("mu0_true|sigma0|beta|R1_K", fit0)
}
data.table::fwrite(data.table::rbindlist(sim100), 
                   "fit/Conquer_no_events_20190715/sim100.csv")
```

\clearpage

# Revised code

```{r comment = NA, echo=FALSE}
cat(readLines("stan/nhppnoevent_lp.stan"), sep = c("\n"))
```

\clearpage
# Estimation results - 500 simulations for each sample size

```{r}
pacman::p_load(data.table, dplyr, ggplot2, purrr)

read_all <- function(file_path = "fit/hierarchical_NHPP20190713/"){
  est_df = file_path %>% 
    list.files() %>% 
    map_dfr(function(file_name){
      fread(paste0(file_path, file_name)) %>% 
        mutate(id = gsub(".csv", "", file_name)) %>% 
        mutate(id = gsub("_.*", "", id)) %>% 
        mutate(id = gsub("sim", "", id)) %>% 
        mutate(id = as.integer(id))
    }) %>% 
    group_by(term, id) %>% 
    summarise(est_mean = mean(estimate),
              est_sd = sd(estimate)) %>% 
    arrange(term, id)

  return(est_df)
}

plot_est = function(data, var = "beta", hline_var = 1.5){
  p = data %>% 
    filter(term == var) %>% 
    ggplot(aes(id, est_mean)) + 
    geom_point() + 
    geom_line(linetype = "dashed", color = "red")+
    geom_errorbar(aes(ymax = est_mean + 1.96*est_sd,
                      ymin = est_mean - 1.96*est_sd), 
                  width = 1)+
    geom_segment(aes(x = 10, xend = 100, 
                     y = hline_var, yend = hline_var), 
                 color = "green")+
    scale_x_continuous(breaks = c(0, 10, 25, 50, 75, 100),
                       labels = c("0", "10", "25", "50", "75", "100")) +
    labs(x = "The number of drivers (random effects)",
         y = var) +
    theme_bw()
  return(p)
}
```


```{r}
est_df1 = read_all("fit/hierarchical_NHPP20190716_lp/")
```



## beta

```{r}
plot_est(est_df1, "beta", 1.5)
```


## mu0

```{r}
plot_est(est_df1, "mu0_true", 0.2)
```


## sigma0

```{r}
plot_est(est_df1, "sigma0", 0.5)
```


## Fixed parameters

```{r}
r1 = plot_est(est_df1, "R1_K[1]", 1)
r2 = plot_est(est_df1, "R1_K[2]", 0.3)
r3 = plot_est(est_df1, "R1_K[3]", 0.2)
```

```{r fig.height=10, fig.width=8}
gridExtra::grid.arrange(r1, r2, r3)
```
